apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudflare-analytics-grafana
  namespace: vixmo
spec:
  schedule: "0 8 * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 600 # 10 min
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 3300 # 55min
      template:
        spec:
          containers:
            - name: cloudflare-analytics
              image: izalul/cloudflare-analytic-grafana:0.1
          restartPolicy: Never
